name: GamemodeCommand
version: 1.0.0
main: de.muv1n.gamemodecommand.GamemodeCommand
api-version: 1.18
description: With this Plugin you can use /gm <0,1,2,3> <Player>, to switch your gamemode
commands:
  gm:
    permission: gamemode.change
permissions:
  gamemode.change:
    default: op